Baikal\ModelBundle\Entity\OAuthAuthCode:
    type: entity
    table: OAuthAuthCode
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY