services:
    baikal_frontend.access_denied_handler:
        class: Baikal\FrontendBundle\Service\AccessDeniedHandler
        arguments:
            - @http_kernel
            - @security.context
            - @router
        tags:
            - { name: kernel.event_listener, event: security.kernel_response, method: handle }


    baikal_frontend.oauth_preloginredirect_formauthenticationentrypoint:
        class: Baikal\FrontendBundle\Service\OAuthPreLoginRedirectFormAuthenticationEntryPoint
        arguments:
            - @http_kernel
            - @security.http_utils
            - 'hello'
            - false